vim.cmd [[let g:netrw_keepdir = 1]]
vim.cmd [[let g:netrw_winsize = 20]]
vim.cmd [[let g:netrw_banner = 0]]
vim.cmd [[hi! link netrwMarkFile Search]]
vim.cmd [[let g:netrw_liststyle = 3]]
vim.cmd [[let g:netrw_altv = 1]]
