(setq user-full-name "yashkarthik")

(load! "configs/svg-config")
(load! "configs/code-config")
(load! "configs/spell-config")
(load! "configs/theme-config")
(load! "configs/latex-config")
(load! "configs/embark-config")
(load! "configs/shell-env-config")
(load! "configs/org-configs/basic")
(load! "configs/org-configs/org-roam-config")
(load! "configs/org-configs/org-alert-config")
(load! "configs/org-configs/org-roam-ui-config")
