-- Fahrenheit colorscheme for Neovim
-- Author: Generated by Claude
-- License: MIT

local M = {}

-- Color palette (matched to terminal colors)
local colors = {
    bg = "#000000",        -- Terminal color 8
    fg = "#ffffce",        -- Terminal color 7
    bg_dark = "#1d1d1d",   -- Terminal color 0
    brown = "#cda074",     -- Terminal color 1
    brown_dark = "#9e744d", -- Terminal color 2
    yellow = "#fecf75",    -- Terminal color 3
    red_dark = "#720102",  -- Terminal color 4
    mauve = "#734c4d",     -- Terminal color 5
    gray = "#979797",      -- Terminal color 6
    cream = "#ffffce",     -- Terminal color 7
    black = "#000000",     -- Terminal color 8
    peach = "#fecea0",     -- Terminal color 9
    orange = "#cc734d",    -- Terminal color 10
    orange_bright = "#fd9f4d", -- Terminal color 11
    red_bright = "#cb4a05", -- Terminal color 12
    blue = "#4e739f",      -- Terminal color 13
    yellow_bright = "#fed04d", -- Terminal color 14
    white = "#ffffff",     -- Terminal color 15
    cursor = "#ffffce",    -- Using cream color for better visibility
    selection_bg = "#4e739f",
    selection_fg = "#ffffce"
}

function M.setup()
    -- Clear existing highlights
    vim.cmd("highlight clear")
    if vim.fn.exists("syntax_on") then
        vim.cmd("syntax reset")
    end

    -- Set colorscheme name
    vim.g.colors_name = "fahrenheit"

    -- Set terminal colors exactly as specified
    vim.g.terminal_color_0 = colors.bg_dark
    vim.g.terminal_color_1 = colors.brown
    vim.g.terminal_color_2 = colors.brown_dark
    vim.g.terminal_color_3 = colors.yellow
    vim.g.terminal_color_4 = colors.red_dark
    vim.g.terminal_color_5 = colors.mauve
    vim.g.terminal_color_6 = colors.gray
    vim.g.terminal_color_7 = colors.cream
    vim.g.terminal_color_8 = colors.black
    vim.g.terminal_color_9 = colors.peach
    vim.g.terminal_color_10 = colors.orange
    vim.g.terminal_color_11 = colors.orange_bright
    vim.g.terminal_color_12 = colors.red_bright
    vim.g.terminal_color_13 = colors.blue
    vim.g.terminal_color_14 = colors.yellow_bright
    vim.g.terminal_color_15 = colors.white

    -- Editor colors
    local groups = {
        -- Editor UI
        Normal = { fg = colors.cream, bg = colors.bg },
        NormalFloat = { fg = colors.cream, bg = colors.bg_dark },
        Cursor = { fg = colors.bg, bg = colors.cursor },
        CursorLine = { bg = colors.bg_dark },
        CursorColumn = { bg = colors.bg_dark },
        LineNr = { fg = colors.gray },
        CursorLineNr = { fg = colors.yellow },
        Visual = { bg = colors.selection_bg, fg = colors.selection_fg },
        VisualNOS = { bg = colors.selection_bg },
        Search = { bg = colors.yellow, fg = colors.bg },
        IncSearch = { bg = colors.orange_bright, fg = colors.bg },
        SignColumn = { bg = colors.bg },
        ColorColumn = { bg = colors.bg_dark },
        Folded = { fg = colors.gray, bg = colors.bg_dark },
        FoldColumn = { fg = colors.gray, bg = colors.bg },
        MatchParen = { fg = colors.yellow_bright, bold = true },
        StatusLine = { fg = colors.cream, bg = colors.bg_dark },
        StatusLineNC = { fg = colors.gray, bg = colors.bg_dark },
        VertSplit = { fg = colors.gray, bg = colors.bg },
        WildMenu = { fg = colors.bg, bg = colors.yellow },
        Directory = { fg = colors.blue },
        Title = { fg = colors.yellow_bright },
        SpecialKey = { fg = colors.gray },
        NonText = { fg = colors.gray },
        MoreMsg = { fg = colors.yellow },
        Question = { fg = colors.yellow },
        WarningMsg = { fg = colors.orange_bright },
        ErrorMsg = { fg = colors.red_bright },

        -- Syntax highlighting
        Comment = { fg = colors.gray },
        Constant = { fg = colors.peach },
        String = { fg = colors.yellow },
        Character = { fg = colors.yellow },
        Number = { fg = colors.orange_bright },
        Boolean = { fg = colors.orange_bright },
        Float = { fg = colors.orange_bright },
        Identifier = { fg = colors.brown },
        Function = { fg = colors.blue },
        Statement = { fg = colors.orange },
        Conditional = { fg = colors.orange },
        Repeat = { fg = colors.orange },
        Label = { fg = colors.orange },
        Operator = { fg = colors.cream },
        Keyword = { fg = colors.orange },
        Exception = { fg = colors.red_bright },
        PreProc = { fg = colors.mauve },
        Include = { fg = colors.mauve },
        Define = { fg = colors.mauve },
        Macro = { fg = colors.mauve },
        PreCondit = { fg = colors.mauve },
        Type = { fg = colors.blue },
        StorageClass = { fg = colors.blue },
        Structure = { fg = colors.blue },
        Typedef = { fg = colors.blue },
        Special = { fg = colors.peach },
        SpecialChar = { fg = colors.peach },
        Tag = { fg = colors.yellow },
        Delimiter = { fg = colors.cream },
        SpecialComment = { fg = colors.gray },
        Debug = { fg = colors.red_bright },
        Underlined = { underline = true },
        Error = { fg = colors.red_bright },
        Todo = { fg = colors.yellow_bright, bold = true },

        -- Plugins
        -- Git signs
        GitSignsAdd = { fg = colors.yellow },
        GitSignsChange = { fg = colors.orange_bright },
        GitSignsDelete = { fg = colors.red_bright },

        -- Indent lines
        IndentBlanklineChar = { fg = colors.bg_dark },

        -- Diagnostic
        DiagnosticError = { fg = colors.red_bright },
        DiagnosticWarn = { fg = colors.orange_bright },
        DiagnosticInfo = { fg = colors.blue },
        DiagnosticHint = { fg = colors.gray },

        -- Treesitter
        ["@keyword"] = { fg = colors.orange },
        ["@string"] = { fg = colors.yellow },
        ["@function"] = { fg = colors.blue },
        ["@function.call"] = { fg = colors.blue },
        ["@field"] = { fg = colors.cream },
        ["@property"] = { fg = colors.cream },
        ["@variable"] = { fg = colors.cream },
        ["@variable.builtin"] = { fg = colors.orange },
        ["@constructor"] = { fg = colors.peach },
        ["@type"] = { fg = colors.blue },
        ["@type.builtin"] = { fg = colors.blue },
        ["@namespace"] = { fg = colors.cream },
        ["@punctuation"] = { fg = colors.cream },
        ["@operator"] = { fg = colors.cream },
        ["@number"] = { fg = colors.orange_bright },
        ["@boolean"] = { fg = colors.orange_bright },
        ["@comment"] = { fg = colors.gray },
    }

    -- Set highlight groups
    for group, settings in pairs(groups) do
        vim.api.nvim_set_hl(0, group, settings)
    end
end

return M
